### PR TITLE
Use std::pair instead of llvm::PointerIntPair.

### PR DESCRIPTION
**Pull request by marsupial**
Fixes issues where symbols are not 16 bit aligned.

### CODE REVIEW

**Comment by vgvassilev** [comment]
I'd appreciate a test case here.

**Comment by marsupial** [comment]
As I said in the email, it will be very difficult to force a symbol to be exported not aligned to 16 bit...Not only for one platform, but reliably for 3, that would take days to make.

The problem is llvm::PointerInPair relies on alignment, that problem does not exists with std::pair.

**Comment by vgvassilev** [comment]
I think adjusting this should be sufficient.
```c++
#define CHECK_SIZE(name, size)                          \
  extern int name##_1[sizeof(name) == size ? 1 : -1];

struct  __attribute__((packed)) {
  int a;
  int b : 4;
  int c : 32;
} s0;
CHECK_SIZE(s0,9)

#pragma pack (1)
struct {
  int a;
  int b : 4;
  int c : 32;
} s1;
CHECK_SIZE(s1,9)
```

**Comment by marsupial** [comment]
I don't know what exactly that code is trying to accomplish, but it is interesting that it crashes cling outright....

As I see it to do the test properly, you can't use a heap allocated symbol, as sometimes the symbol would be aligned properly, sometimes not...so you'd have to construct a binary to do this.

If you know an easier way or am seeing something I'm not that why not just write the test?

**Comment by vgvassilev** [comment]
Merged, thanks for your quick followup and contribution!

**Pull request closed without merging**
