### PR TITLE
InputValidator fixes

### PR DESCRIPTION
**Pull request by marsupial**

### CODE REVIEW

**Comment by karies** [comment]
Great! Alas, this causes a problem in ROOT with this file:
```
$ cat roottest/cling/specialobj/write.C
{
   gROOT->ProcessLine(".L AthIndex.h+");
   gROOT->ProcessLine(".L T0Result.h+");
   gROOT->ProcessLine(".L calib.h+");

#ifdef ClingWorkAroundMissingDynamicScope
   TObject *calib = 0;
   calib = (TObject*)gROOT->ProcessLine("new RTCalib;");
#else
   RTCalib *calib = new RTCalib;
#endif
   TFile* f = TFile::Open("tmp.root", "recreate");
   calib->Write();
   f->Close();

}
```
namely
```
Processing roottest/cling/specialobj/write.C...
Error in cling::MetaProcessor: file write.C is incomplete (missing parenthesis or similar)!
```
Could you have a look, please?

**Comment by marsupial** [comment]
I cannot as roottest never worked here, and ROOT is now failing at CMake configuration.

**Comment by pcanal** [comment]
>  ROOT is now failing at CMake configuration.
How is it failing?

**Comment by marsupial** [comment]
I'll email you so I can attach the logs.

**Comment by marsupial** [comment]
That error seems to be from MetaProcessor::readInputFromFile.
That function seems to be transforming the file contents in a variety of ways.

**Comment by marsupial** [comment]
Fixed.
There were also a few problems in MetaProcessor::readInputFromFile, including an API misuse which was the trigger.

**Comment by karies** [comment]
Thanks! I see some more failures from this PR, namely tutorial-graphics-tmathtext, roottest-cling-return-constRetrunTest_WILL_FAIL, roottest-cling-typedef_global-scopeTest2, roottest-root-collection-execTClonesArrayAbsorb-auto - and roottest is still running.

The first issue seems to be due to a change in the resulting Value for readInputFromFile. I will debug this tomorrow and try to fix this myself, as well as cross check the other failures.

**Comment by marsupial** [comment]
Again, I don't care if the last commit is discarded. It would be more efficient to call:
`m_Interp.process(content, result);
`
As meta-commands weren't called with the prior behavior (past the first line) anyway.

**Comment by karies** [comment]
roottest-root-treeformula-array-make fails with
1334: Error in cling::MetaProcessor: file runmultidim.C is incomplete (missing parenthesis or similar)!

even after removing the last commit. I'll debug tomorrow unless you get to it still today.

**Comment by marsupial** [comment]
My guess is the the lines:
`if (_file0)
{`

Could you try collapsing it to:
`if (_file0) {`

**Comment by marsupial** [comment]
Fixed. Though the file `runmultidim.C` proves the last commit should be ignored or the new argument defaulted to false.

**Comment by karies** [comment]
Merged with new argument defaulted to false, as you suggested. Thanks a lot!

**Pull request closed without merging**
