### PR TITLE
Fix unloading of extern "C" declarations.

### PR DESCRIPTION
**Pull request by marsupial**
First step to get printValue unloading working properly.

### CODE REVIEW

**Comment by karies** [comment]
Awesome, thanks! Merged! Give us more unloading and Windows, please! :-)

**Comment by marsupial** [comment]
I'll see what can be picked cleanly. Hopefully there should be some fixes for friendship and namespace/using declarations.  Going further there needs to be a discussion:

Both the DeclUnloading and Windows fixes are dependent on changes to clang. For the unloading, I don't foresee any issues as it's a nice patch that just adds error reporting instead of clang's asserts.
The Windows edits is a more obscure change that allows cling to use COFF as the JIT format. As it seems you don't _truely_ support Windows yet I hope it won't be an issue as it makes 20+ test pass.

And finally since there would have to be patches to LLVM, I upgraded to both LLVM-3.9-release and recently went to LLVM-4.0-release so if you were planning to do an LLVM upgrade it might be a good time. (I don't think either the unloading or COFF patches require the upgrade).

Let me know your thought on this...(preferably by e-mail if they are longer).

**Comment by karies** [comment]
Will reply by email.

test/CodeUnloading/ExternC.C fails on all platforms but Mac (i.e. fails on all Linux flavors we test):

```
#0 0x00000000009bcbb5 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9bcbb5)
#1 0x00000000009bad6e llvm::sys::RunSignalHandlers() (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9bad6e)
#2 0x00000000009baeaa SignalHandler(int) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9baeaa)
#3 0x00002b16cc34fcb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
#4 0x000000000099e725 llvm::formatted_raw_ostream::ComputePosition(char const*, unsigned long) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x99e725)
#5 0x000000000099e7c2 llvm::formatted_raw_ostream::write_impl(char const*, unsigned long) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x99e7c2)
#6 0x00000000009ac134 llvm::raw_ostream::write(char const*, unsigned long) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9ac134)
#7 0x0000000002512ce4 llvm::Module::print(llvm::raw_ostream&, llvm::AssemblyAnnotationWriter*, bool, bool) const (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x2512ce4)
#8 0x00000000008e486e cling::ClangInternalState::printLLVMModule(llvm::raw_ostream&, llvm::Module const&, clang::CodeGenerator&) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x8e486e)
#9 0x00000000008f6372 cling::ClangInternalState::store() (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x8f6372)
#10 0x00000000008f645c cling::ClangInternalState::ClangInternalState(clang::ASTContext const&, clang::Preprocessor const&, llvm::Module const*, clang::CodeGenerator*, std::string const&) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x8f645c)
#11 0x00000000008f64ca cling::ClangInternalState::compare(std::string const&, bool) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x8f64ca)
#12 0x00000000009391c1 cling::Interpreter::compareInterpreterState(std::string const&) const (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9391c1)
#13 0x000000000097d655 cling::MetaSema::actOncompareStateCommand(llvm::StringRef) const (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x97d655)
#14 0x0000000000979935 cling::MetaParser::iscompareStateCommand() (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x979935)
#15 0x000000000097a6be cling::MetaParser::isCommand(cling::MetaSema::ActionResult&, cling::Value*) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x97a6be)
#16 0x000000000097b021 cling::MetaProcessor::process(char const*, cling::Interpreter::CompilationResult&, cling::Value*) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x97b021)
#17 0x00000000009c44f1 cling::UserInterface::runInteractively(bool) (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x9c44f1)
#18 0x0000000000886f94 main (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x886f94)
#19 0x00002b16cc33af45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
#20 0x00000000008b7d5d _start (/mnt/build/workspace/cling-generic-build/BUILDTYPE/Release/COMPILER/native/LABEL/ubuntu14/obj/./bin/cling+0x8b7d5d)
```

Could you send a PR that fixes this?

**Comment by marsupial** [comment]
Ok, it may take a while though...that looks bizarre.

**Comment by marsupial** [comment]
Ok, the problem seems to be line **10** of **test/CodeUnloading/ExternC.C**
`int atexit(void (*)(void));`
Removing that line fixes it here.

On Linux `atexit` is really `atexit nothrow()` which causes an error in compilation. This messes up the test as one Transaction fails, and the amount of **.undo** submitted later is one more than it should be (i.e. it unwinds cling to 0 transactions instead of the first).

I'll do a PR, but it might be quicker for you just to edit, as I want to test/make sure #94 fixes the crash because of this error.

**Comment by marsupial** [comment]
The fix for this was put in a separate PR #97.

**Pull request closed without merging**
