### PR TITLE
Move DeclUnloader and ParserStateRAII into cling namespace.

### PR DESCRIPTION
**Pull request by marsupial**
Requires changes to clang here:
https://github.com/marsupial/clang/commit/bb84e42bcd751fdc10024b9e2a0c66c3c7afadc1

### CODE REVIEW

**Comment by marsupial** [comment]
Added additional commit in front to keep recent CMake changes closer/nicer in repo.

**Comment by marsupial** [comment]
Added additional commits for comments, and conflict resolution.

**Comment by marsupial** [comment]
But who knows if or when that would get in?
I'm of the opinion things should be in their proper namespace, both for the obvious reasons and it makes it clearer for new authors to understand which code is cling specific.

**Comment by karies** [comment]
@vgvassilev "Can we simplify the patch in clang by reverting +friend class ::cling::ParserStateRAII;? We should submit the ParserStateRAII to clang's mainline." - yes, but should we block further development for something we plan to do since what - three years? I.e. we should do what you suggest but until it's in we should keep going.

**Comment by vgvassilev** [comment]
@marsupial I am positive that I could get it on the fast lane for a review and check it in.
@karies How keeping ParserStateRAII where it is blocks you. It seems we are generating extra work from refactorings which we agree are temporary.

**Comment by marsupial** [comment]
Even if it makes it into clang at most you'd have avoided editing all of 3 lines...this conversation has taken longer than that would have!

If it makes into into clang I have no problem fixing this if it made it into cling or still a PR, but I'm going to have to decline doing the extra work on a possibility it gets in. 

FWIW I submitted this because unless these changes make it into master I have to continually cherry-pick it onto the tip of every branch so I can test locally before submitting PRs. Having them bundled into one commit is just much easier to manage.

**Comment by vgvassilev** [comment]
I'd have really preferred our patches to clang to become less not more. Piling up patches makes upgrades to newer llvm/clang versions really hard.

If this makes things really more convenient for you I am inclined to accept it.

**Comment by karies** [comment]
...and just a side note: once it's accepted into clang we'll still need to bump cling's llvm/clang revision to benefit from it. So the turn-around even for fast-path is weeks.

**Comment by karies** [comment]
Sorry think fingers didn't mean to close...

**Comment by vgvassilev** [comment]
Ok, let's integrate it and I will try to offload this patch in clang. @karies could you take over this PR while I am working on submitting the patch to clang?

**Comment by karies** [comment]
Taken. LGT*Y*, @vgvassilev ?

**Comment by vgvassilev** [comment]
Yes.

**Comment by karies** [comment]
Merged, together with your clang patch marsupial/clang@bb84e42 - thanks!

**Pull request closed without merging**
