### PR TITLE
Syntax fixes for VisualStudio < 2015.

### PR DESCRIPTION
**Pull request by marsupial**

### CODE REVIEW

**Comment by vgvassilev** [comment]
@bellenot could you review, please?

**Comment by bellenot** [comment]
Fine with me

**Comment by vgvassilev** [comment]
Let's wait for green builds and 'almost green' windows build and I can merge it.

**Comment by vgvassilev** [comment]
Integrated. Thank you for your contribution!

We also should add a Visual Studio 14 to our appveyor builds.

**Pull request closed without merging**
